data:extend({
  {
    type = "int-setting",
    name = "xtreme-fishing-ugpipestart",
    setting_type = "startup",
    default_value = 11,
    minimum_value = 1,
    maximum_value = 101,
  },
  {
    type = "int-setting",
    name = "xtreme-fishing-ugpipeinterval",
    setting_type = "startup",
    default_value = 2,
    minimum_value = 0,
    maximum_value = 16,
  },
  {
    type = "int-setting",
    name = "xtreme-fishing-waterpercycle",
    setting_type = "startup",
    default_value = 250,
    minimum_value = 50,
    maximum_value = 500,
  },
  {
    type = "string-setting",
    name = "xtreme-fishing-puffer_type",
    setting_type = "startup",
    default_value = "coal",
    allow_blank = false,
    auto_trim = true
  },
  {
    type = "int-setting",
    name = "xtreme-fishing-puffer_yield",
    setting_type = "startup",
    default_value = 6,
    minimum_value = 1,
    maximum_value = 100,
  },
  {
    type = "int-setting",
    name = "xtreme-fishing-squid_oil",
    setting_type = "startup",
    default_value = 10,
    minimum_value = 5,
    maximum_value = 100,
  },
  {
    type = "int-setting",
    name = "xtreme-fishing-puffer_gas",
    setting_type = "startup",
    default_value = 10,
    minimum_value = 5,
    maximum_value = 100,
  },
  {
    type = "int-setting",
    name = "xtreme-fishing-crab_plastic",
    setting_type = "startup",
    default_value = 2,
    minimum_value = 1,
    maximum_value = 10,
  },
  {
    type = "int-setting",
    name = "xtreme-fishing-fishlube",
    setting_type = "startup",
    default_value = 10,
    minimum_value = 5,
    maximum_value = 100,
  },
})
